import json
import os
import sys
from pathlib import Path

# All logic utilizing the library pathlib is generated by Claude Code (Gemini).
class ConfigLoader:
    def __init__(self):
        # Gemini added this line of code to create config.json in the user's Appdata folder, depending on OS
        if sys.platform == "win32":
            base_dir = Path(os.environ.get('LOCALAPPDATA', '.'))
        elif sys.platform == "darwin":
            base_dir = Path.home() / 'Library' / 'Application Support'
        else:
            # QuickType doesn't support an OS other than windows and mac. Here be dragons!
            base_dir = Path.home() / '.config'

        self.config_file_path = base_dir / 'QuickType' / 'config.json'

        # Gemini added this whole if statement that adds the file at the directory if it isn't present
        if not os.path.exists(self.config_file_path):
            self.config_file_path.parent.mkdir(parents=True, exist_ok=True)
            with open(self.config_file_path, "w", encoding='utf-8') as file:
                json.dump({"trigger_character": ":", "reload_character": "`", "shortcuts": {}}, file, indent=4)

        self.load()

    def load(self):
        # Gemini added the encoding='utf-8' to fix a bug where some characters were not recognized
        with open(self.config_file_path, "r", encoding='utf-8') as file:
            data = json.load(file)
            self.trigger_character = data.get("trigger_character", ":")
            self.reload_character = data.get("reload_character", "`")
            self.shortcuts = data.get("shortcuts", {})
