import json
import os
from pathlib import Path

# All logic utilizing the library pathlib is generated by Claude Code (Gemini).
class ConfigLoader:
    def __init__(self):
        # Gemini added this line of code to create config.json in the user's Appdata/Local/QuickType
        self.config_file_path = Path(os.environ.get('LOCALAPPDATA', '.')) / 'QuickType' / 'config.json'

        # Gemini added this whole if statement that adds the file at the directory if it isn't present
        if not os.path.exists(self.config_file_path):
            self.config_file_path.parent.mkdir(parents=True, exist_ok=True)
            with open(self.config_file_path, "w", encoding='utf-8') as file:
                json.dump({"trigger_character": ":", "shortcuts": {}}, file, indent=4)

        self.trigger_character = ":"
        self.shortcuts = {}
        self.load()

    def load(self):
        # Gemini added the encoding='utf-8' to fix a bug where some characters were not recognized
        with open(self.config_file_path, "r", encoding='utf-8') as file:
            data = json.load(file)
            self.trigger_character = data.get("trigger_character", ":")
            self.shortcuts = data.get("shortcuts", {})
